#!/usr/bin/perl
# File: mutt_ldap_query
#
# Description: searches ldap for email addresses
#
# Requires: perl-LDAP
#
# Author: Nathan Straz <nstraz@redhat.com> : 20091201
# Based on script by: Kiat Huang <khuang@redhat.com> : 20041217

use Net::LDAP;
use Data::Dumper;
my $term = shift @ARGV;
$filter = "(&(|(cn=*$term*)(uid=$term))(mail=*))";
$ldap_server="ldap.rdu.redhat.com";
$search_base="dc=redhat,dc=com";
$ldap = Net::LDAP->new($ldap_server) or die "$@";
$ldap->bind;
$mesg = $ldap->search(
		base => $search_base,
		filter => $filter,
		attrs => [ "cn", "mail", "title"]
	);

if ($mesg->code == 0) {
	foreach my $entry ($mesg->entries) {
		my $mail = $entry->get_value('mail');
		my $cn = $entry->get_value('cn');
		my $title = $entry->get_value('title');
		print "$mail\t$cn\t$title\n";
	}
} else {
  die $mesg->error;
}
